version: '3'
services:
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    restart: always
    environment:
      VIRTUAL_HOST: unifi.feliciterra.com
      VIRTUAL_PORT: 8443
      VIRTUAL_PROTO: https
      LETSENCRYPT_EMAIL: brookeandmatthew@gmail.com
      LETSENCRYPT_HOST: unifi.feliciterra.com
    volumes:
      - ./data/unifi:/unifi
    ports:
      - "8080:8080/tcp"
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "10001:10001/udp"
    networks:
      - webproxy
  # plex:
  #   container_name: plex
  #   image: plexinc/pms-docker:plexpass
  #   network_mode: host
  #   restart: always
  #   environment:
  #     VIRTUAL_HOST: plex.feliciterra.com
  #   env_file:
  #     - .env
  #   volumes:
  #     - /opt/services/data/plex/config:/config
  #     - /opt/services/data/plex/transcode:/transcode
  #     - /opt/services/data/plex/data:/data
  openvpn:
    container_name: openvpn
    # https://github.com/kylemanna/docker-openvpn
    image: kylemanna/openvpn:latest
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./data/openvpn/conf:/etc/openvpn
  samba:
    container_name: samba
    # https://github.com/dperson/samba
    image: dperson/samba:latest
    network_mode: host
    restart: always
    command:
      - -r
      - -n
      - -W
      - -s
      - "Feliciterra Files;/fileshare;yes;no;yes;${SHARE_USER};${SHARE_USER}"
      - -u
      - "${SHARE_USER};${SHARE_PASSWORD}"
    env_file:
      - .env
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - ./data/samba/conf:/etc/samba
      - ./data/fileshare:/fileshare

  # Dummy containers to enable Let's Encrypt automations with nginx proxy setup.
  homeassistant-proxy:
    image: cwempe/docker-dummy
    container_name: proxy-dummy-homeassistant
    restart: always
    environment:
      VIRTUAL_HOST: homeassistant.feliciterra.com
      VIRTUAL_PORT: 8123
      UPSTREAM_NAME: 10.0.0.101
      LETSENCRYPT_EMAIL: brookeandmatthew@gmail.com
      LETSENCRYPT_HOST: homeassistant.feliciterra.com
    networks:
      - webproxy
  homeassistant-ide-proxy:
    image: cwempe/docker-dummy
    container_name: proxy-dummy-homeassistant-ide
    restart: always
    environment:
      VIRTUAL_HOST: ide.homeassistant.feliciterra.com
      VIRTUAL_PORT: 8321
      UPSTREAM_NAME: 10.0.0.101
      LETSENCRYPT_EMAIL: brookeandmatthew@gmail.com
      LETSENCRYPT_HOST: ide.homeassistant.feliciterra.com
    networks:
      - webproxy
  homeassistant-flows-proxy:
    image: cwempe/docker-dummy
    container_name: proxy-dummy-homeassistant-flows
    restart: always
    environment:
      VIRTUAL_HOST: flows.homeassistant.feliciterra.com
      VIRTUAL_PORT: 1880
      UPSTREAM_NAME: 10.0.0.101
      LETSENCRYPT_EMAIL: brookeandmatthew@gmail.com
      LETSENCRYPT_HOST: flows.homeassistant.feliciterra.com

networks:
  webproxy:
    external:
      name: webproxy
