version: '3'
services:
  letsencrypt:
    container_name: letsencrypt
    image: csmith/letsencrypt-lexicon:latest
    restart: always
    environment:
      EMAIL: brookeandmatthew@gmail.com
      PROVIDER: 'dnsimple'
      ACCEPT_CA_TERMS: 'true'
    env_file:
      - .env
    volumes:
      - ./data/letsencrypt:/letsencrypt
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:unifi5
    network_mode: host
    restart: always
    volumes:
      - ./data/unifi/data:/unifi/data
      - ./data/unifi/log:/unifi/log
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/unifi/cert:ro
    ports:
      - "8080:8080"
      - "8443:8443"
      # Guest portal ports
      # - "8843:8843"
      - "3478:3478"
      - "6789:6789"
      - "10001:10001/udp"
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - ./data/plex/data:/data
    # ports:
    #   - 32400:32400/tcp
    #   - 3005:3005/tcp
    #   - 8324:8324/tcp
    #   - 32469:32469/tcp
    #   - 1900:1900/udp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./data/openvpn/conf:/etc/openvpn
  samba:
    container_name: samba
    image: dperson/samba
    network_mode: host
    restart: always
    command: -r -p -s "Feliciterra Files;/fileshare/shared;yes;no;no;all" -s "Feliciterra Archive;/fileshare/archive;yes;no;no;all"
    environment:
      NMDB: "1"
      WORKGROUP: HOMEGROUP
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - ./data/samba/conf:/etc/samba
      - ./data/fileshare/shared:/fileshare/shared
      - ./data/fileshare/archive:/fileshare/archive
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    network_mode: host
    # ports:
    #   - "8123:8123"
    restart: always
    volumes:
      - ./data/home-assistant:/config
      - ./data/letsencrypt:/letsencrypt:ro
