version: '3'
services:
  hassio_db:
    container_name: hassio_db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432/tcp
    volumes:
      - ./data/hassio_db/data:/var/lib/postgresql/data/pgdata
      - ./data/hassio_db/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: hassio
      POSTGRES_DB: hassio
    env_file:
      - .env
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    restart: always
    volumes:
      - ./data/unifi:/unifi
    ports:
      - "8443:8443/tcp"
      - "8080:8080/tcp"
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "10001:10001/udp"
  openvpn:
    container_name: openvpn
    # https://github.com/kylemanna/docker-openvpn
    image: kylemanna/openvpn:latest
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./data/openvpn/conf:/etc/openvpn
  samba:
    container_name: samba
    # https://github.com/dperson/samba
    image: dperson/samba:latest
    network_mode: host
    restart: always
    command:
      - -r
      - -n
      - -W
      - -s
      - "Feliciterra Files;/fileshare;yes;no;yes;${SHARE_USER};${SHARE_USER}"
      - -u
      - "${SHARE_USER};${SHARE_PASSWORD}"
    env_file:
      - .env
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - ./data/samba/conf:/etc/samba
      - ./data/fileshare:/fileshare
