version: '3'
services:
  services-logger:
    container_name: services-logger
    image: logzio/logzio-docker
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  letsencrypt:
    container_name: letsencrypt
    image: csmith/letsencrypt-lexicon:latest
    restart: always
    environment:
      EMAIL: brookeandmatthew@gmail.com
      PROVIDER: 'dnsimple'
      ACCEPT_CA_TERMS: 'true'
      ALGORITHM: rsa
    env_file:
      - .env
    volumes:
      - ./data/letsencrypt:/letsencrypt
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    network_mode: host
    restart: always
    volumes:
      - ./data/unifi:/unifi
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/unifi/cert
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - ./data/plex/data:/data
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/letsencrypt:ro
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./data/openvpn/conf:/etc/openvpn
  samba:
    container_name: samba
    image: dperson/samba
    network_mode: host
    restart: always
    command: -r -p -s "Feliciterra Files;/fileshare/shared;yes;no;no;all" -s "Feliciterra Archive;/fileshare/archive;yes;no;no;all"
    environment:
      NMDB: "1"
      WORKGROUP: HOMEGROUP
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - ./data/samba/conf:/etc/samba
      - ./data/fileshare/shared:/fileshare/shared
      - ./data/fileshare/archive:/fileshare/archive
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    network_mode: host
    restart: always
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - ./data/home-assistant:/config
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/letsencrypt:ro
  ha-appdaemon:
    container_name: ha-appdaemon
    image: acockburn/appdaemon
    restart: always
    ports:
      - 5050:5050
    env_file:
      - .env
    volumes:
      - ./data/ha-appdaemon:/conf
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/letsencrypt:ro
