version: '3'
services:
  # services-logger:
  #   container_name: services-logger
  #   image: logzio/logzio-docker:latest
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  letsencrypt:
    container_name: letsencrypt
    image: csmith/letsencrypt-lexicon:latest
    restart: always
    environment:
      EMAIL: brookeandmatthew@gmail.com
      PROVIDER: 'dnsimple'
      ACCEPT_CA_TERMS: 'true'
      ALGORITHM: rsa
    env_file:
      - .env
    volumes:
      - /opt/services/data/letsencrypt:/letsencrypt
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    network_mode: host
    restart: always
    volumes:
      - /opt/services/data/unifi:/unifi
      - /opt/services/data/letsencrypt/certs/gateway.feliciterra.com:/unifi/cert
  # plex:
  #   container_name: plex
  #   image: plexinc/pms-docker:plexpass
  #   network_mode: host
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - /opt/services/data/plex/config:/config
  #     - /opt/services/data/plex/transcode:/transcode
  #     - /opt/services/data/plex/data:/data
  #     - /opt/services/data/letsencrypt/certs/gateway.feliciterra.com:/letsencrypt:ro
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn:latest
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - /opt/services/data/openvpn/conf:/etc/openvpn
  # samba:
  #   container_name: samba
  #   image: dperson/samba:latest
  #   network_mode: host
  #   restart: always
  #   command: -r -p -s "Feliciterra Files;/fileshare/shared;yes;no;no;all" -s "Feliciterra Archive;/fileshare/archive;yes;no;no;all"
  #   environment:
  #     NMDB: "1"
  #     WORKGROUP: HOMEGROUP
  #   ports:
  #     - "139:139"
  #     - "445:445"
  #     - "137:137/udp"
  #     - "138:138/udp"
  #   volumes:
  #     - /opt/services/data/samba/conf:/etc/samba
  #     - /opt/services/data/fileshare/shared:/fileshare/shared
  #     - /opt/services/data/fileshare/archive:/fileshare/archive
