version: '3'
services:
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:unifi5
    network_mode: host
    restart: always
    environment:
      TZ: "America/Chicago"
    volumes:
     - ./data/unifi/data:/var/lib/unifi
     - ./data/unifi/logs:/var/log/unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      # Guest portal ports
      # - "8843:8843"
      - "3478:3478"
      - "6789:6789"
      - "10001:10001/udp"
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart: always
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-G26ZknnQzTZvuJyU1UwP
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - ./data/plex/data:/data
    # ports:
    #   - 32400:32400/tcp
    #   - 3005:3005/tcp
    #   - 8324:8324/tcp
    #   - 32469:32469/tcp
    #   - 1900:1900/udp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./data/openvpn/conf:/etc/openvpn
