version: '3'
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      #- CLI_ARGS= #optional
    env_file:
      - .env
      - calibre/.env
    volumes:
      - calibre-library:/config
    ports:
      - 8180:8080
      - 8181:8081
    restart: unless-stopped
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - calibre-web:/config
      - calibre-library:/books
    ports:
      - 8183:8083
    restart: unless-stopped
  hassio_db:
    container_name: hassio-db
    image: docker.pkg.github.com/pho3nixf1re/feliciterra-server/hassio-db:latest
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    volumes:
      - hassio_db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: hassio
      POSTGRES_DB: hassio
    env_file:
      - .env
      - hassio-db/.env
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - SERVERURL=wireguard.feliciterra.com
      - SERVERPORT=51820
      - PEERS=mturney,bjturney
      - PEERDNS=10.0.0.1
      # - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=10.13.13.1,10.0.0.0/24
    volumes:
      - wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  openvpn:
    container_name: openvpn
    image: docker.pkg.github.com/pho3nixf1re/feliciterra-server/openvpn:latest
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - openvpn:/etc/openvpn
    env_file:
      - .env
  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8080:8080"
    depends_on:
      - hassio_db
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://hassio:GhpcC5X6L2MnuOjTbxIgfawqzEikZ1@10.0.0.110/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
    env_file:
      - .env
      - hasura/.env

volumes:
  hassio_db:
  openvpn:
  calibre-library:
  calibre-web:
  wireguard:
