version: '3'
services:
  hassio_db:
    container_name: hassio-db
    image: docker.pkg.github.com/pho3nixf1re/feliciterra-server/hassio-db:latest
    restart: always
    ports:
      - 5432:5432/tcp
    volumes:
      - hassio_db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: hassio
      POSTGRES_DB: hassio
    env_file:
      - .env
      - hassio-db/.env
  openvpn:
    container_name: openvpn
    image: docker.pkg.github.com/pho3nixf1re/feliciterra-server/openvpn:latest
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - openvpn:/etc/openvpn
    env_file:
      - .env
  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8080:8080"
    depends_on:
      - hassio_db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://hassio:GhpcC5X6L2MnuOjTbxIgfawqzEikZ1@10.0.0.110/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
    env_file:
      - .env
      - .env.template

volumes:
  hassio_db:
  openvpn:
