version: '3'
services:
  hassio_db:
    container_name: hassio-db
    image: docker.pkg.github.com/pho3nixf1re/feliciterra-server/hassio-db:latest
    restart: always
    ports:
      - 5432:5432/tcp
    volumes:
      - hassio_db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: hassio
      POSTGRES_DB: hassio
    env_file:
      - .env
  openvpn:
    container_name: openvpn
    image: docker.pkg.github.com/pho3nixf1re/feliciterra-server/openvpn:latest
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - openvpn:/etc/openvpn

volumes:
  hassio_db:
  openvpn:
